development:
  adapter: postgresql
  encoding: unicode
  database: amanikids_cards_development
  pool: 5
  username: <%= Etc.getlogin %>
  password:

test: &TEST
  adapter: postgresql
  encoding: unicode
  database: amanikids_cards_test
  pool: 5
  username: <%= Etc.getlogin %>
  password:

cucumber:
  <<: *TEST
