common: &default_settings
  app_name: Cards

  license_key: '<%= ENV['NEWRELIC_LICENSE_KEY'] %>'

  enabled: false
  log_level: info
  ssl: false
  apdex_t: 0.5
  capture_params: false

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500

  error_collector:
    enabled: true
    capture_source: true

development:
  <<: *default_settings
  enabled: false
  developer: true

test:
  <<: *default_settings
  enabled: false

production:
  <<: *default_settings
  enabled: true
